package com.biostime.app.settings.entity;

// Generated 2016-1-27 11:46:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DlOaInterfaceLogId generated by hbm2java
 */
@Embeddable
public class DlOaInterfaceLogId implements java.io.Serializable {

	private String oaApplyId;
	private String interfaceName;
	private String inParam;
	private String handleResult;
	private String handleMessage;
	private String applyTime;
	private Date insertTime;

	public DlOaInterfaceLogId() {
	}

	public DlOaInterfaceLogId(String oaApplyId, String interfaceName,
			String inParam, String handleResult, String handleMessage,
			String applyTime, Date insertTime) {
		this.oaApplyId = oaApplyId;
		this.interfaceName = interfaceName;
		this.inParam = inParam;
		this.handleResult = handleResult;
		this.handleMessage = handleMessage;
		this.applyTime = applyTime;
		this.insertTime = insertTime;
	}

	@Column(name = "OA_APPLY_ID", length = 50)
	public String getOaApplyId() {
		return this.oaApplyId;
	}

	public void setOaApplyId(String oaApplyId) {
		this.oaApplyId = oaApplyId;
	}

	@Column(name = "INTERFACE_NAME", length = 150)
	public String getInterfaceName() {
		return this.interfaceName;
	}

	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}

	@Column(name = "IN_PARAM", length = 4000)
	public String getInParam() {
		return this.inParam;
	}

	public void setInParam(String inParam) {
		this.inParam = inParam;
	}

	@Column(name = "HANDLE_RESULT", length = 100)
	public String getHandleResult() {
		return this.handleResult;
	}

	public void setHandleResult(String handleResult) {
		this.handleResult = handleResult;
	}

	@Column(name = "HANDLE_MESSAGE", length = 150)
	public String getHandleMessage() {
		return this.handleMessage;
	}

	public void setHandleMessage(String handleMessage) {
		this.handleMessage = handleMessage;
	}

	@Column(name = "APPLY_TIME", length = 50)
	public String getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(String applyTime) {
		this.applyTime = applyTime;
	}

	@Column(name = "INSERT_TIME", length = 7)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DlOaInterfaceLogId))
			return false;
		DlOaInterfaceLogId castOther = (DlOaInterfaceLogId) other;

		return ((this.getOaApplyId() == castOther.getOaApplyId()) || (this
				.getOaApplyId() != null && castOther.getOaApplyId() != null && this
				.getOaApplyId().equals(castOther.getOaApplyId())))
				&& ((this.getInterfaceName() == castOther.getInterfaceName()) || (this
						.getInterfaceName() != null
						&& castOther.getInterfaceName() != null && this
						.getInterfaceName()
						.equals(castOther.getInterfaceName())))
				&& ((this.getInParam() == castOther.getInParam()) || (this
						.getInParam() != null && castOther.getInParam() != null && this
						.getInParam().equals(castOther.getInParam())))
				&& ((this.getHandleResult() == castOther.getHandleResult()) || (this
						.getHandleResult() != null
						&& castOther.getHandleResult() != null && this
						.getHandleResult().equals(castOther.getHandleResult())))
				&& ((this.getHandleMessage() == castOther.getHandleMessage()) || (this
						.getHandleMessage() != null
						&& castOther.getHandleMessage() != null && this
						.getHandleMessage()
						.equals(castOther.getHandleMessage())))
				&& ((this.getApplyTime() == castOther.getApplyTime()) || (this
						.getApplyTime() != null
						&& castOther.getApplyTime() != null && this
						.getApplyTime().equals(castOther.getApplyTime())))
				&& ((this.getInsertTime() == castOther.getInsertTime()) || (this
						.getInsertTime() != null
						&& castOther.getInsertTime() != null && this
						.getInsertTime().equals(castOther.getInsertTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOaApplyId() == null ? 0 : this.getOaApplyId().hashCode());
		result = 37
				* result
				+ (getInterfaceName() == null ? 0 : this.getInterfaceName()
						.hashCode());
		result = 37 * result
				+ (getInParam() == null ? 0 : this.getInParam().hashCode());
		result = 37
				* result
				+ (getHandleResult() == null ? 0 : this.getHandleResult()
						.hashCode());
		result = 37
				* result
				+ (getHandleMessage() == null ? 0 : this.getHandleMessage()
						.hashCode());
		result = 37 * result
				+ (getApplyTime() == null ? 0 : this.getApplyTime().hashCode());
		result = 37
				* result
				+ (getInsertTime() == null ? 0 : this.getInsertTime()
						.hashCode());
		return result;
	}

}
